waypoints:
- ow: 0.999999999999967
  ox: 2.2710470971148163e-07
  oy: 1.2033260174365001e-07
  oz: 2.5755146215531295e-09
  x: 1.0035623794804158
  y: 0.9999999728338159
  z: 0.0
- ow: 0.999999371358405
  ox: 3.008911617609028e-05
  oy: -0.0011182415304108306
  oz: -7.689811191759927e-05
  x: 1.0559826241683368
  y: 1.0000021517124873
  z: 0.0
- ow: 0.999999880246613
  ox: 1.5806282690951996e-06
  oy: -0.00048082652979638234
  oz: -9.115980328174491e-05
  x: 1.1178310344137816
  y: 0.9999944237133045
  z: 0.0
- ow: 0.9999896633866414
  ox: 4.987482288922813e-07
  oy: -0.004546454995173376
  oz: 5.354063745093125e-05
  x: 2.240178426877099
  y: 0.9999395629399025
  z: 0.0
- ow: 0.8537594068096688
  ox: -0.007976456988322356
  oy: -0.013086720290564869
  oz: -0.5204421093358537
  x: 3.2898892313739068
  y: -0.2843289396751374
  z: 0.0
- ow: 0.8538522852566656
  ox: 2.6109651119920904e-07
  oy: -4.598522464416679e-07
  oz: -0.5205153935876349
  x: 3.3694749770620276
  y: -0.43874513133908866
  z: 0.0
