waypoints:
- ow: 0.9999999999987503
  ox: -1.2824294316434519e-06
  oy: 9.116394570826247e-07
  oz: 1.5372225979440644e-07
  x: 0.004100309656469686
  y: -0.9999994411982064
  z: 0.0
- ow: 0.9999999999072101
  ox: 5.7659181112018746e-08
  oy: -1.3534099449139114e-05
  oz: 1.5507765811774844e-06
  x: 0.05691971569747249
  y: -0.9999999492502647
  z: 0.0
- ow: 0.9999662901070671
  ox: 8.153080875495977e-07
  oy: -0.008210844470645953
  oz: -2.611366380579043e-05
  x: 1.655732587039803
  y: -1.0000505796986583
  z: 0.0
- ow: 0.9994271985368035
  ox: -8.553284835588326e-07
  oy: -0.03384185409008793
  oz: -6.11219323548211e-05
  x: 4.650792432569063
  y: -1.0003180210258529
  z: 0.0
- ow: 0.9991606743667274
  ox: -5.07311055611208e-06
  oy: -0.04096261604831213
  oz: -0.00010421021447554017
  x: 5.976424936138662
  y: -1.000539706353345
  z: 0.0
- ow: 0.9999999308262829
  ox: -6.719372180843233e-06
  oy: -4.325018607049552e-05
  oz: -0.0003693666214909813
  x: 6.030009484938251
  y: -1.0006646055450144
  z: 0.0
- ow: 0.9999999253575499
  ox: 3.80034172931367e-07
  oy: 1.106710725366502e-07
  oz: -0.00038637383195535874
  x: 6.397820285078939
  y: -1.000940588873735
  z: 0.0
- ow: 0.999999835979088
  ox: -1.4874712839753185e-07
  oy: -0.00043001362769170615
  oz: -0.00037832532938845775
  x: 6.751736657425445
  y: -1.001217330879253
  z: 0.0
