waypoints:
- ow: 0.999999999999967
  ox: 2.2706142350380453e-07
  oy: 1.2053801525523153e-07
  oz: 2.59195961165081e-09
  x: 0.00355847106328663
  y: 0.9999999728362716
  z: 0.0
- ow: 0.9999999958174502
  ox: -1.5106217892092267e-08
  oy: -9.146091068102356e-05
  oz: 3.334867300635704e-08
  x: 0.062261901145924434
  y: 0.9999998284747162
  z: 0.0
- ow: 0.9998615432512308
  ox: 1.7797167133864542e-06
  oy: 0.016640108766366932
  oz: 3.32316637440015e-05
  x: -1.3672006161796009
  y: 0.999848937637272
  z: 0.0
- ow: 0.9991847197400532
  ox: 1.3418013009799168e-07
  oy: 0.04037196810455381
  oz: 5.416486772868359e-06
  x: -4.064089403711479
  y: 0.9997741711459799
  z: 0.0
- ow: 0.9995500505750279
  ox: -5.535421272817927e-07
  oy: 0.029994933266694043
  oz: 1.932561091051772e-05
  x: -4.701698742241897
  y: 0.9997244192577284
  z: 0.0
- ow: 0.9999981789257701
  ox: 1.8677982194447164e-05
  oy: -0.001908344583156156
  oz: 4.15070799612601e-06
  x: -4.758087128976403
  y: 0.9997387303105799
  z: 0.0
- ow: 0.9999999994487064
  ox: 3.628131142754523e-07
  oy: -7.08072722653667e-08
  oz: 3.320317343683888e-05
  x: -5.553103350800399
  y: 0.9997274795085369
  z: 0.0
- ow: 0.9999998000201062
  ox: 2.471696408522705e-05
  oy: 0.0006319405163288528
  oz: 5.671321062448568e-08
  x: -5.501229840975449
  y: 0.9997276591827223
  z: 0.0
- ow: 0.9996673197215584
  ox: -2.332580689717587e-07
  oy: -0.025792415813571147
  oz: -3.4163740380344786e-05
  x: -2.5059897468084267
  y: 0.9995980258888518
  z: 0.0
- ow: 0.9986429170768227
  ox: -5.230538941467045e-06
  oy: -0.05207993934536007
  oz: -6.373946164618658e-05
  x: 0.503669019275602
  y: 0.9993200244643606
  z: 0.0
- ow: 0.9982645969385345
  ox: -5.1773473679983985e-06
  oy: -0.058887913252707196
  oz: -9.025010841244185e-05
  x: 2.198920449747747
  y: 0.9990779221737385
  z: 0.0
- ow: 0.9999610750086758
  ox: -1.1579130882380112e-06
  oy: -0.008822309490102624
  oz: -0.00012377969717212997
  x: 2.208274689939914
  y: 0.9990688411343936
  z: 0.0
